name: Deploy Backend to HF Spaces

on:
  push:
    branches: [master]
    paths:
      - backend/**
  workflow_dispatch: # Allows running manually

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "bot@huggingface.co"
          git config --global user.name "Hugging Face Bot"
          # Split the backend dir into a new branch
          git subtree split --prefix backend -b hf-deploy
          # Force push that branch to the remote main branch
          git push https://saptarshiroy39:$HF_TOKEN@huggingface.co/spaces/saptarshiroy39/Cipher hf-deploy:main --force
