name: Deploy Backend to HF Spaces

on:
  push:
    branches: [master]
    paths:
      - backend/**
  workflow_dispatch: # Allows running manually

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync to Hugging Face
        uses: nateraw/huggingface-sync-action@v0.0.4
        with:
          github_repo_id: saptarshiroy39/Cipher
          huggingface_repo_id: saptarshiroy39/Cipher
          repo_type: space
          space_sdk: docker
          hf_token: ${{ secrets.HF_TOKEN }}
          github_dir: backend
